# Generated by Django 6.0.4 on 2026-04-22 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_perfil_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='documento',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='grado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='perfil',
            name='unidad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
