# Generated by Django 6.0.4 on 2026-04-22 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_perfil_documento_perfil_estado_perfil_grado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='documento',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
