# Generated by Django 6.0.4 on 2026-05-08 05:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_perfil_documento_alter_perfil_rol_curso_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batallon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('ciudad', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cuadros', models.ManyToManyField(blank=True, related_name='batallones_cuadro', to=settings.AUTH_USER_MODEL)),
                ('soldados', models.ManyToManyField(blank=True, related_name='batallones_soldado', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
