# Generated by Django 6.0.4 on 2026-05-08 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_batallon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batallon',
            name='codigo',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
