# Generated by Django 6.0.4 on 2026-05-08 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_alter_batallon_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='batallon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal', to='usuarios.batallon'),
        ),
    ]
