# Generated by Django 6.0.4 on 2026-05-12 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_compania'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='compania',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal', to='usuarios.compania'),
        ),
    ]
