# Generated by Django 5.0.4 on 2026-05-14 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_alter_archivocurso_id_alter_asistencia_id_and_more'),
    ]

    operations = [
    ]
