from .auth_views import *
from .dashboard_views import *
from .usuarios_views import *
from .batallones_views import *
from .evaluaciones_views import *
from .extras_views import *
from .instructor_views import *
from .biometrico import *
from .crear_test_views import *
from .resolver_test_views import *
